import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apple iPhone",
  description: "Generated by create next app",
  // icons: {
  //   icon: [
  //     {
  //       // media: '(prefers-color-scheme: light)',
  //       url: '../../public/assets/images/apple.svg',
  //       href: '../../public/assets/images/apple.svg',
  //     }
  //   ]
  // }    
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
